version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
    expose:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      database:
        condition: service_healthy
  database:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    expose:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    healthcheck:
      test: /usr/bin/pg_isready
      start_period: 5s
      interval: 10s
      timeout: 10s
      retries: 5
